### ISSUE TITLE
官网下载的版本中有个插件存在重大安全漏洞 lib/webuploader

### ISSUE THREAD

**Issue by yangfancn** [jackying/h-ui#29]
文件位置 : `/lib/webuploader/0.1.5/server/preview.php`
![image](https://user-images.githubusercontent.com/42950770/144553565-104ca5fd-36f2-4f7e-8dd4-09f6fff3dda8.png)
没有做任何文件后缀限制，可被直接上传php文件等
我几十个网站因此被上传后门文件，挂马，跳到博彩网站
为什么这里又没有这个插件呢？？不会是你们内部人员留的后门吧？

**Comment by yangfancn** [comment]
错了，是在 h-ui.admin 项目中的

**Comment by jackying** [comment]
ueditor、webuploader  这两个组件中php文件是上传的服务端demo，是让写服务端的人参考用的，可以完全删除掉。

**Comment by jackying** [comment]
很多人不会写服务端的上传，所以插件中带了demo代码，记着要删除。
